services:
    app:
        build:
            context: .
            dockerfile: Dockerfile
        image: laravel-gss
        container_name: laravel_gss_app
        restart: unless-stopped
        working_dir: /var/www
        volumes:
            - .:/var/www:delegated
        environment:
            APP_ENV: local
            APP_DEBUG: true
            APP_KEY: ${APP_KEY}
            DB_HOST: db
            DB_PORT: 3306
            DB_DATABASE: gecorp
            DB_USERNAME: root
            DB_PASSWORD: root
        depends_on:
            - db

    webserver:
        image: nginx:alpine
        container_name: laravel_gss_nginx
        restart: unless-stopped
        ports:
            - "8008:80"
        volumes:
            - .:/var/www:delegated
            - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
        depends_on:
            - app

    db:
        image: mysql:8.0
        container_name: laravel_gss_db
        restart: unless-stopped
        environment:
            MYSQL_DATABASE: gecorp
            MYSQL_ROOT_PASSWORD: root
        ports:
            - "3306:3306"
        volumes:
            - dbdata:/var/lib/mysql

volumes:
    dbdata:
